// Role requirements + learning resources shared by readiness, mentor, and roadmap flows.

export type Requirement = {
  skill: string;
  importance: "core" | "helpful";
  why: string;
  resources: { label: string; kind: "course" | "project" | "practice" }[];
};

const requirement = (
  skill: string,
  importance: Requirement["importance"],
  why: string,
  resources: Requirement["resources"],
): Requirement => ({ skill, importance, why, resources });

export const ROLE_REQUIREMENTS: Record<string, Requirement[]> = {
  default: [
    requirement("Programming fundamentals", "core", "Write clear, testable programs in a language used by your target teams.", [{ label: "Build a small tested program", kind: "project" }]),
    requirement("Git & GitHub", "core", "Collaborate through branches, pull requests, and code review.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("SQL", "helpful", "Query and model data used by modern applications.", [{ label: "Design + query a small schema", kind: "project" }]),
    requirement("Testing", "helpful", "Use automated checks to make changes safely.", [{ label: "Add a regression test suite", kind: "project" }]),
    requirement("System Design", "helpful", "Explain how reliable software is structured and scaled.", [{ label: "Design a URL shortener", kind: "practice" }]),
  ],
  "software engineer": [
    requirement("Programming fundamentals", "core", "Write clear, testable programs in a language used by your target teams.", [{ label: "Build a small tested program", kind: "project" }]),
    requirement("Git & GitHub", "core", "Collaborate through branches, pull requests, and code review.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("SQL", "helpful", "Query and model data used by modern applications.", [{ label: "Design + query a small schema", kind: "project" }]),
    requirement("Testing", "helpful", "Use automated checks to make changes safely.", [{ label: "Add a regression test suite", kind: "project" }]),
    requirement("System Design", "helpful", "Explain how reliable software is structured and scaled.", [{ label: "Design a URL shortener", kind: "practice" }]),
  ],
  "frontend engineer": [
    requirement("HTML/CSS", "core", "Build accessible, responsive interfaces from solid web fundamentals.", [{ label: "Build a responsive landing page", kind: "project" }]),
    requirement("JavaScript", "core", "Create interactive browser experiences with confidence.", [{ label: "JavaScript browser exercises", kind: "practice" }]),
    requirement("React", "core", "Build maintainable component-based user interfaces.", [{ label: "React foundations", kind: "course" }]),
    requirement("TypeScript", "core", "Make frontend code safer and easier to evolve in a team.", [{ label: "Convert a React project to TypeScript", kind: "project" }]),
    requirement("Git & GitHub", "core", "Collaborate through branches, pull requests, and code review.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("Testing", "helpful", "Protect user-facing behavior with reliable automated tests.", [{ label: "Add component tests", kind: "project" }]),
    requirement("API integration", "helpful", "Connect interfaces to real services and handle loading and error states.", [{ label: "Build a data-driven frontend", kind: "project" }]),
    requirement("Deployment", "helpful", "Ship a frontend so others can use and evaluate it.", [{ label: "Deploy a frontend application", kind: "project" }]),
  ],
  "backend engineer": [
    requirement("Backend fundamentals", "core", "Design reliable server-side programs and services.", [{ label: "Build a REST service", kind: "project" }]),
    requirement("SQL", "core", "Persist and query application data safely and efficiently.", [{ label: "Design + query a small schema", kind: "project" }]),
    requirement("APIs", "core", "Expose predictable interfaces for clients and integrations.", [{ label: "Build and document an API", kind: "project" }]),
    requirement("Git & GitHub", "core", "Collaborate through branches, pull requests, and code review.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("Authentication", "core", "Protect user accounts and application resources.", [{ label: "Add authentication to an API", kind: "project" }]),
    requirement("Docker", "helpful", "Run backend services consistently across environments.", [{ label: "Containerise one of your repos", kind: "project" }]),
    requirement("Testing", "helpful", "Verify service behavior before it reaches production.", [{ label: "Add API integration tests", kind: "project" }]),
    requirement("Deployment", "helpful", "Operate a backend service in a hosted environment.", [{ label: "Deploy an API", kind: "project" }]),
  ],
  "full stack engineer": [
    requirement("HTML/CSS", "core", "Build accessible, responsive interfaces from solid web fundamentals.", [{ label: "Build a responsive landing page", kind: "project" }]),
    requirement("JavaScript", "core", "Create interactive browser experiences with confidence.", [{ label: "JavaScript browser exercises", kind: "practice" }]),
    requirement("React", "core", "Build maintainable component-based user interfaces.", [{ label: "React foundations", kind: "course" }]),
    requirement("Backend/API development", "core", "Connect user experiences to reliable server-side behavior.", [{ label: "Build a full-stack feature", kind: "project" }]),
    requirement("SQL", "core", "Persist and query application data safely and efficiently.", [{ label: "Design + query a small schema", kind: "project" }]),
    requirement("Authentication", "core", "Protect user accounts and application resources.", [{ label: "Add authentication to an application", kind: "project" }]),
    requirement("Testing", "helpful", "Verify behavior across the frontend and backend.", [{ label: "Add full-stack tests", kind: "project" }]),
    requirement("Git & GitHub", "helpful", "Collaborate through branches, pull requests, and code review.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("Docker", "helpful", "Run the complete application consistently across environments.", [{ label: "Containerise a full-stack app", kind: "project" }]),
    requirement("Deployment", "helpful", "Ship a complete application so others can use it.", [{ label: "Deploy a full-stack application", kind: "project" }]),
    requirement("System Design", "helpful", "Design boundaries between clients, services, and data.", [{ label: "Design a full-stack system", kind: "practice" }]),
  ],
  sre: [
    requirement("Linux", "core", "Operate and automate production systems from the command line.", [{ label: "Linux operations lab", kind: "practice" }]),
    requirement("Networking", "core", "Diagnose how services communicate and where failures occur.", [{ label: "Map a service network", kind: "project" }]),
    requirement("Git", "core", "Review and automate operational changes safely.", [{ label: "Manage an operations repository", kind: "project" }]),
    requirement("Cloud", "core", "Operate services and infrastructure in a cloud environment.", [{ label: "Deploy a service to the cloud", kind: "project" }]),
    requirement("Observability", "core", "Make system behavior visible through useful signals.", [{ label: "Instrument a service", kind: "project" }]),
    requirement("Monitoring", "core", "Detect and investigate service degradation early.", [{ label: "Create service monitors", kind: "project" }]),
    requirement("Logging", "helpful", "Turn events into searchable operational evidence.", [{ label: "Build a structured logging pipeline", kind: "project" }]),
    requirement("Incident Response", "helpful", "Respond to incidents with calm, repeatable procedures.", [{ label: "Write an incident playbook", kind: "project" }]),
    requirement("Reliability Engineering", "helpful", "Design systems around failure budgets and dependable operation.", [{ label: "Run a reliability review", kind: "project" }]),
    requirement("SLIs/SLOs/SLAs", "helpful", "Set measurable service objectives and communicate them clearly.", [{ label: "Define service objectives", kind: "project" }]),
    requirement("Scalability", "helpful", "Reason about capacity, bottlenecks, and graceful growth.", [{ label: "Load test a service", kind: "project" }]),
    requirement("Disaster Recovery", "helpful", "Recover services and data when normal operation fails.", [{ label: "Test a recovery plan", kind: "project" }]),
  ],
  "data engineer": [
    requirement("Python", "core", "Build maintainable programs for data processing.", [{ label: "Build a data-cleaning CLI", kind: "project" }]),
    requirement("SQL", "core", "Query and transform data efficiently and safely.", [{ label: "Design + query a warehouse schema", kind: "project" }]),
    requirement("Databases", "core", "Choose and operate storage for reliable data products.", [{ label: "Compare database designs", kind: "project" }]),
    requirement("ETL/ELT", "core", "Move raw data into trustworthy analytical forms.", [{ label: "Build an ETL pipeline", kind: "project" }]),
    requirement("Data Pipelines", "core", "Design repeatable, observable flows of data.", [{ label: "Build a pipeline with retries", kind: "project" }]),
    requirement("Data Warehouses", "helpful", "Model data for analytical workloads and reporting.", [{ label: "Model a warehouse", kind: "project" }]),
    requirement("Cloud", "helpful", "Operate data workloads on a cloud platform.", [{ label: "Deploy a data workload", kind: "project" }]),
    requirement("Spark/Distributed Processing", "helpful", "Process datasets that exceed a single machine.", [{ label: "Process a large dataset", kind: "project" }]),
    requirement("Orchestration", "helpful", "Schedule, monitor, and recover data workflows.", [{ label: "Orchestrate a daily pipeline", kind: "project" }]),
    requirement("Data Quality", "helpful", "Detect and prevent incorrect data from reaching users.", [{ label: "Add data quality checks", kind: "project" }]),
  ],
  "ml engineer": [
    requirement("Python", "core", "Build production-minded data and machine learning systems.", [{ label: "Python for Everybody", kind: "course" }]),
    requirement("Statistics", "core", "Understand uncertainty and measure model behavior.", [{ label: "Applied statistics practice", kind: "practice" }]),
    requirement("Machine Learning", "core", "Train models that solve measurable problems.", [{ label: "Build a machine learning project", kind: "project" }]),
    requirement("Deep Learning", "core", "Use neural networks for complex representations and tasks.", [{ label: "Train a neural network", kind: "project" }]),
    requirement("Model Evaluation", "core", "Validate models and recognize failure modes.", [{ label: "Compare and evaluate models", kind: "practice" }]),
    requirement("APIs", "helpful", "Expose models as usable services and integrations.", [{ label: "Serve a model through an API", kind: "project" }]),
    requirement("Docker", "helpful", "Package experiments and services reproducibly.", [{ label: "Containerise a model service", kind: "project" }]),
    requirement("Cloud", "helpful", "Operate training and inference workloads in the cloud.", [{ label: "Deploy a model workload", kind: "project" }]),
    requirement("Model Deployment", "helpful", "Release models as reliable products.", [{ label: "Deploy a model service", kind: "project" }]),
    requirement("MLOps", "helpful", "Automate the lifecycle from experiment to production.", [{ label: "Create an MLOps pipeline", kind: "project" }]),
    requirement("Monitoring", "helpful", "Detect drift and production model failures.", [{ label: "Monitor model behavior", kind: "project" }]),
  ],
  "full stack developer": [
    requirement("HTML/CSS", "core", "Build accessible, responsive interfaces from solid web fundamentals.", [{ label: "Build a responsive landing page", kind: "project" }]),
    requirement("JavaScript", "core", "Create interactive browser experiences with confidence.", [{ label: "JavaScript browser exercises", kind: "practice" }]),
    requirement("React", "core", "Build maintainable component-based user interfaces.", [{ label: "React foundations", kind: "course" }]),
    requirement("TypeScript", "core", "Make full-stack code safer and easier to evolve.", [{ label: "Convert a project to TypeScript", kind: "project" }]),
    requirement("Backend/API development", "core", "Connect user experiences to reliable server-side behavior.", [{ label: "Build a full-stack feature", kind: "project" }]),
    requirement("SQL", "core", "Persist and query application data safely and efficiently.", [{ label: "Design + query a small schema", kind: "project" }]),
    requirement("Git & GitHub", "helpful", "Collaborate through branches, pull requests, and code review.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("Docker", "helpful", "Run the complete application consistently across environments.", [{ label: "Containerise a full-stack app", kind: "project" }]),
  ],
  "data scientist": [
    requirement("Python", "core", "Use Python to explore data and build reproducible analyses.", [{ label: "Python for Everybody", kind: "course" }]),
    requirement("SQL", "core", "Retrieve and shape data from relational systems.", [{ label: "SQLBolt exercises", kind: "practice" }]),
    requirement("Statistics", "core", "Reason about uncertainty, patterns, and meaningful results.", [{ label: "Statistics practice problems", kind: "practice" }]),
    requirement("NumPy/Pandas", "core", "Clean, transform, and analyze datasets efficiently.", [{ label: "Analyze a messy dataset", kind: "project" }]),
    requirement("Data Visualization", "core", "Communicate findings through clear, honest visualizations.", [{ label: "Create an exploratory dashboard", kind: "project" }]),
    requirement("Machine Learning", "helpful", "Train models that answer useful predictive questions.", [{ label: "Build a machine learning project", kind: "project" }]),
    requirement("Model Evaluation", "helpful", "Measure model quality and recognize failure modes.", [{ label: "Compare and evaluate models", kind: "practice" }]),
    requirement("Data Projects", "helpful", "Show end-to-end analysis through evidence-backed projects.", [{ label: "Publish a data science case study", kind: "project" }]),
  ],
  "data analyst": [
    requirement("SQL", "core", "Retrieve and shape business data from relational systems.", [{ label: "SQLBolt exercises", kind: "practice" }]),
    requirement("Excel/Spreadsheets", "core", "Analyze and communicate structured data in familiar tools.", [{ label: "Build a spreadsheet analysis", kind: "project" }]),
    requirement("Python", "core", "Automate repeatable analysis and data preparation.", [{ label: "Build a data-cleaning CLI", kind: "project" }]),
    requirement("Statistics", "core", "Interpret trends and uncertainty without overclaiming.", [{ label: "Statistics practice problems", kind: "practice" }]),
    requirement("Data Visualization", "core", "Turn analysis into clear decisions and narratives.", [{ label: "Create an exploratory dashboard", kind: "project" }]),
    requirement("Power BI/Tableau", "helpful", "Build dashboards that stakeholders can explore.", [{ label: "Publish a BI dashboard", kind: "project" }]),
    requirement("Data Cleaning", "helpful", "Make raw data consistent enough to support trustworthy analysis.", [{ label: "Clean a messy business dataset", kind: "project" }]),
    requirement("Data Projects", "helpful", "Demonstrate analysis from question to recommendation.", [{ label: "Publish an analysis case study", kind: "project" }]),
  ],
  "ai/ml engineer": [
    requirement("Python", "core", "Build production-minded data and machine learning systems.", [{ label: "Python for Everybody", kind: "course" }]),
    requirement("Mathematics/Statistics", "core", "Understand the mathematical behavior of learning algorithms.", [{ label: "Applied statistics practice", kind: "practice" }]),
    requirement("NumPy/Pandas", "core", "Prepare numerical data for experiments and training.", [{ label: "Prepare a model dataset", kind: "project" }]),
    requirement("Machine Learning", "core", "Train models that solve measurable problems.", [{ label: "Build a machine learning project", kind: "project" }]),
    requirement("Deep Learning", "core", "Use neural networks for complex representations and tasks.", [{ label: "Train a neural network", kind: "project" }]),
    requirement("Model Evaluation", "helpful", "Validate models and monitor their real-world behavior.", [{ label: "Compare and evaluate models", kind: "practice" }]),
    requirement("APIs", "helpful", "Expose models as usable services and integrations.", [{ label: "Serve a model through an API", kind: "project" }]),
    requirement("Docker", "helpful", "Package experiments and services reproducibly.", [{ label: "Containerise a model service", kind: "project" }]),
  ],
  "devops engineer": [
    requirement("Linux", "core", "Operate systems and automate work from the command line.", [{ label: "Linux command-line practice", kind: "practice" }]),
    requirement("Shell/Bash", "core", "Automate repeatable operational work with shell scripts.", [{ label: "Write an operations script", kind: "project" }]),
    requirement("Git & GitHub", "core", "Version infrastructure and collaborate safely.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("Networking", "core", "Understand how services communicate and where failures occur.", [{ label: "Map a service network", kind: "project" }]),
    requirement("CI/CD", "core", "Automate checks and reliable software delivery.", [{ label: "Create a deployment pipeline", kind: "project" }]),
    requirement("Docker", "core", "Package services consistently for local and hosted environments.", [{ label: "Containerise an application", kind: "project" }]),
    requirement("Kubernetes", "helpful", "Manage containerized workloads at larger scale.", [{ label: "Deploy an app to Kubernetes", kind: "project" }]),
    requirement("Infrastructure as Code", "helpful", "Make infrastructure repeatable, reviewable, and recoverable.", [{ label: "Define infrastructure as code", kind: "project" }]),
    requirement("Cloud", "helpful", "Provision and operate services on a cloud platform.", [{ label: "Deploy a service to the cloud", kind: "project" }]),
    requirement("Monitoring", "helpful", "Detect service degradation and infrastructure failures early.", [{ label: "Create service monitors", kind: "project" }]),
    requirement("Security", "helpful", "Operate infrastructure with secure defaults and least privilege.", [{ label: "Harden a deployment", kind: "project" }]),
    requirement("Incident Response", "helpful", "Respond to operational incidents with repeatable procedures.", [{ label: "Write an incident playbook", kind: "project" }]),
  ],
  "mobile developer": [
    requirement("Kotlin or Swift", "core", "Build native mobile applications with the platform language.", [{ label: "Complete native language exercises", kind: "practice" }]),
    requirement("Mobile fundamentals", "core", "Work with mobile lifecycle, navigation, and device constraints.", [{ label: "Build a multi-screen mobile app", kind: "project" }]),
    requirement("UI development", "core", "Create accessible interfaces that work across device sizes.", [{ label: "Build a mobile interface", kind: "project" }]),
    requirement("APIs", "core", "Connect mobile experiences to reliable services.", [{ label: "Integrate a mobile API", kind: "project" }]),
    requirement("Local storage", "core", "Persist useful data when connectivity is limited.", [{ label: "Add offline storage", kind: "project" }]),
    requirement("Git & GitHub", "helpful", "Collaborate and review mobile code changes.", [{ label: "Branch, review, merge a real repo", kind: "project" }]),
    requirement("Testing", "helpful", "Keep mobile behavior reliable across devices and releases.", [{ label: "Add mobile tests", kind: "project" }]),
    requirement("App deployment", "helpful", "Package and release an app for real users.", [{ label: "Prepare an app release", kind: "project" }]),
  ],
  "cybersecurity engineer": [
    requirement("Networking", "core", "Understand traffic, protocols, and common attack surfaces.", [{ label: "Map and inspect a test network", kind: "project" }]),
    requirement("Linux", "core", "Operate and investigate systems from the command line.", [{ label: "Linux command-line practice", kind: "practice" }]),
    requirement("Security fundamentals", "core", "Apply core principles for protecting systems and data.", [{ label: "Security fundamentals course", kind: "course" }]),
    requirement("Python/scripting", "core", "Automate defensive checks and repeatable investigations.", [{ label: "Build a security automation script", kind: "project" }]),
    requirement("Web security", "core", "Recognize and mitigate common web vulnerabilities.", [{ label: "Secure a vulnerable demo app", kind: "project" }]),
    requirement("Authentication", "helpful", "Protect identities, sessions, and access boundaries.", [{ label: "Review an authentication flow", kind: "practice" }]),
    requirement("Security testing", "helpful", "Find weaknesses through controlled, responsible testing.", [{ label: "Run a security test lab", kind: "project" }]),
    requirement("Incident/security tooling", "helpful", "Investigate signals and respond using practical tooling.", [{ label: "Build an incident response playbook", kind: "project" }]),
  ],
};

export function requirementsForRole(role?: string): Requirement[] {
  const normalizedRole = role?.trim().toLowerCase().replace(/\s+/g, " ") ?? "";
  const aliases: Record<string, string> = {
    "software developer": "software engineer",
    "frontend developer": "frontend engineer",
    "front end engineer": "frontend engineer",
    "front-end engineer": "frontend engineer",
    "backend developer": "backend engineer",
    "back end engineer": "backend engineer",
    "back-end engineer": "backend engineer",
    "full-stack developer": "full stack developer",
    "fullstack developer": "full stack developer",
    "full stack engineer": "full stack engineer",
    "fullstack engineer": "full stack engineer",
    "ai ml engineer": "ai/ml engineer",
    "machine learning engineer": "ai/ml engineer",
    "ml engineer": "ml engineer",
    devops: "devops engineer",
    "site reliability engineer": "sre",
    "sre engineer": "sre",
    "cyber security engineer": "cybersecurity engineer",
    "cyber-security engineer": "cybersecurity engineer",
  };
  return ROLE_REQUIREMENTS[aliases[normalizedRole] ?? normalizedRole] ?? ROLE_REQUIREMENTS.default;
}
